name: Publish new version
run-name: Publish new ${{ inputs.bump }} version from ${{ github.ref_name }} by @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      bump:
        description: 'Positionals'
        required: true
        type: choice
        default: 'build'
        options:
          - major
          - minor
          - patch
          - build

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.actor }}
  cancel-in-progress: true

jobs:
  publish-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Generate Version
        id: generate_version
        run: |
          git config user.name ${{ github.actor }}
          git config user.email ${{ github.actor }}@users.noreply.github.com
          if [ ${{ inputs.bump }} == major ]; then BUMP='premajor'; fi
          if [ ${{ inputs.bump }} == minor ]; then BUMP='preminor'; fi
          if [ ${{ inputs.bump }} == patch ]; then BUMP='prepatch'; fi
          if [ ${{ inputs.bump }} == build ]; then BUMP='prerelease'; fi
          npm version $BUMP --preid build
          git push origin ${{ github.ref }}
          echo "version=$(git describe --tags --abbrev=0)" >> "$GITHUB_OUTPUT"
      - name: Push Git Tag
        run: |
          git push origin ${{ steps.generate_version.outputs.version }}
    outputs:
      version: ${{ steps.generate_version.outputs.version }}

  create-release:
    needs: publish-version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ needs.publish-version.outputs.version }}
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.publish-version.outputs.version }}
          release_name: Release - ${{ needs.publish-version.outputs.version }}
          draft: false
          prerelease: false
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
      version: ${{ needs.publish-version.outputs.version }}
