name: Publish Docker image
run-name: Publish Docker image ${{ inputs.bump }} version from ${{ github.ref_name }} by @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      platforms:
        description: Image platforms (you can specify multiple platforms separated by comma)
        required: true
        type: string
        default: linux/amd64,linux/arm64

jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: gulabs/gu-blockscout-frontend
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      - name: Add SHORT_SHA env property with commit short sha
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
      - name: Debug
        env:
          REF_TYPE: ${{ github.ref_type }}
          REF_NAME: ${{ github.ref_name }}
        run: |
          echo "ref_type: $REF_TYPE"
          echo "ref_name: $REF_NAME"
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          cache-from: type=gha
          tags: gulabs/gu-blockscout-frontend:${{ github.ref_name }}
          platforms: ${{ inputs.platforms }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            GIT_COMMIT_SHA=${{ env.SHORT_SHA }}
            GIT_TAG=${{ github.ref_type == 'tag' && github.ref_name || '' }}
            ${{ inputs.build_args }}
